[project]
name = "robostack"
version = "0.1.0"
description = "Development environment for RoboStack ROS packages"
authors = ["Your Name <your.email@example.com>"]
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-aarch64"]

[activation]
scripts = ["install/setup.sh"]

[target.linux.dependencies]
libgl-devel = "*"

[environments]
default = { features = ["jazzy"] }

[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[dependencies]
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
cmake = ">=3.31.5,<4"
ninja = ">=1.12.1,<2"
pyserial-asyncio = ">=0.6,<0.7"
pyserial = ">=3.5,<4"
numpy = ">=1.26.4,<2"
ros-jazzy-ament-cmake-auto = ">=2.5.3,<3"
compilers = ">=1.9.0,<2"
pkg-config = ">=0.29.2,<0.30"
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-ros2-control = ">=4.23.0,<5"
ros-jazzy-ros2-controllers = ">=4.18.0,<5"
ros-jazzy-pluginlib = ">=5.4.2,<6"

[tasks]
# build = "colcon build --symlink-install"
build = {cmd = "colcon build --symlink-install", inputs = ["src"]}
