version: "3.3"
services:
  ros2ubuntu:
    container_name: ros2ubuntu
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ipc: host
    network_mode: host
    privileged: true
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - ..:/root/FinalYearProject
      - $HOME/.Xauthority:/tmp/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
    devices:
      - "/dev/video0:/dev/video0"
    command: ["tail", "-f", "/dev/null"]
